# Generated by Django 3.0.7 on 2020-06-20 22:41

from django.db import migrations
from cv_worker.operations.models import Operation


def add_ping(apps, schema_editor):
    if Operation.objects.filter(name='ping_cv_worker').exists():
        return
    operation = Operation(
      name='ping_cv_worker',
      description='basic ping operation',
      status='ACTIVE',
    )
    operation.save()

def delete_ping(apps, schema_editor):
    if not Operation.objects.filter(name='ping_cv_worker').exists():
        return
    Operation.objects.filter(name='ping_cv_worker').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_ping, delete_ping),
    ]


