# Generated by Django 3.0.7 on 2020-06-20 16:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=36)),
                ('description', models.CharField(max_length=255)),
                ('request_data', models.TextField(null=True)),
                ('response_data', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.Operation')),
            ],
        ),
    ]
